config/routes.rb
Rails.application.routes.draw do

  devise_for :users, path: '/', only: :omniauth_callbacks,
                    controllers: { omniauth_callbacks: 'omniauth_callbacks' }

  scope '(:locale)', locale: /en/ do

    get 'main_pages/home'

    devise_for :users, path_names: { sign_in: 'login', sign_out: 'logout' }, skip: :omniauth_callbacks,
                        controllers: { registrations: 'registrations' }
    devise_scope :user do
      get 'login', to: 'devise/sessions#new'
      match '/users/:id/finish_signup' => 'registrations#finish_signup', via: [:get, :patch], :as => :finish_signup
    end
    
    ActiveAdmin.routes(self)

    resources :products do
      get 'page/:page', action: :index, on: :collection
    end
    resource :product do
      resources :reviews
    end
    
    mount EngineCart::Engine, at: "/cart"
    get '/orders', :to => 'engine_cart/orders#index', :as => :orders
    get '/orders/:id', :to => 'engine_cart/orders#show', :as => :order

    get '/:locale' => 'main_pages#home'
    root 'main_pages#home'
  end
end

app/controllers/main_pages_controller.rb
class MainPagesController < ApplicationController
  
  def home
    category_sort = params[:category].present? ? params[:category] : @categories.default_sort.first
    @products = Product.with_category(category_sort)
    @lattest_products = @products.lattest_products(2).decorate
    @best_sellers = @products.best_sellers.limit(4).decorate
  end
end

app/views/main_pages/home.html.haml
%main.container
  #slider.carousel.slide{'data-ride': "carousel"}
    %ol.carousel-indicators.general-carousel-indicators
      %li.active{'data-target': "#slider", 'data-slide-to': "0"}
      %li{'data-target': "#slider", 'data-slide-to': "1"}
    .carousel-inner{role: "listbox"}
      - @lattest_products.each_with_index do |product, i|
        .item{class: ("active" if i == 0)}
          .row
            .col-sm-5
              .general-img-wrap
                %a{href: product_path(product)}
                  %img.img-shadow.general-thumbnail-img.width-full{src: "#{product.product_pictures(1).first.image_path}"}
            .col-sm-7
              .mb-60
                %h1= product.title
                %p.lead.shorten-description= product.description
                %p.in-grey-600.small= product.all_authors
                .general-align.pt-20
                  %a.btn.btn-primary{href: engine_cart.cart_path('order_item[product_id]': product.id, 'order_item[quantity]': 1), 'data-method': 'put'}= t('.buy_now')
    %a.left.carousel-control{href: "#slider", role: "button", 'data-slide': "prev"}
      %span.icon-prev{'aria-hidden': "true"}
      %span.sr-only= t(:previous)
    %a.right.carousel-control{href: "#slider", role: "button", 'data-slide': "next"}
      %span.icon-next{'aria-hidden': "true"}
      %span.sr-only= t(:next)
.container
  .jumbotron.text-center.mb-0
    %h2.h1= t('.welcome')
    .mb-res-50
      %p.in-grey-600= t('.home_msg')
    = link_to t('.get_started'), products_path, class: 'btn btn-default'
  .mb-35
    %h3= t('.best_sellers')
    .row
      - @best_sellers.each do |product|
        .col-sm-6.col-md-3
          .general-thumb-wrap
            .thumbnail.general-thumbnail
              %img.img-shadow.general-thumbnail-img{src: "#{product.product_pictures(1).first.image_path}"}
              .thumb-hover
                .general-thumb-link-wrap
                  %a.thumb-hover-link{href: product_path(product)}
                    %i.fa.fa-eye.thumb-icon{'aria-hidden': "true"}
                  %a.thumb-hover-link{href: engine_cart.cart_path('order_item[product_id]': product.id, 'order_item[quantity]': 1), 'data-method': 'put'}
                    %i.fa.fa-shopping-cart.thumb-icon
          .mb-35
            .clearfix
              %p.pull-right.font-16.in-gold-500= number_to_currency(product.price_value)
              %p.general-title.mr-55.product_fixed_height= product.title
            %span.divider-sm
            %p.in-grey-600.small= product.all_authors