config/routes.rb
Rails.application.routes.draw do

  devise_for :users, path: '/', only: :omniauth_callbacks,
                    controllers: { omniauth_callbacks: 'omniauth_callbacks' }

  scope '(:locale)', locale: /en/ do

    get 'main_pages/home'

    devise_for :users, path_names: { sign_in: 'login', sign_out: 'logout' }, skip: :omniauth_callbacks,
                        controllers: { registrations: 'registrations' }
    devise_scope :user do
      get 'login', to: 'devise/sessions#new'
      match '/users/:id/finish_signup' => 'registrations#finish_signup', via: [:get, :patch], :as => :finish_signup
    end
    
    ActiveAdmin.routes(self)

    resources :products do
      get 'page/:page', action: :index, on: :collection
    end
    resource :product do
      resources :reviews
    end
    
    mount EngineCart::Engine, at: "/cart"
    get '/orders', :to => 'engine_cart/orders#index', :as => :orders
    get '/orders/:id', :to => 'engine_cart/orders#show', :as => :order

    get '/:locale' => 'main_pages#home'
    root 'main_pages#home'
  end
end

app/views/engine_cart/carts/show.html.haml
%main.container.general-main-wrap
  %h1.general-title-margin Cart
  .visible-xs
    = form_tag cart_path,  method: :put do |field|
      - @order_items.each  do |order_item|
        .general-cart-item.divider-lg-bottom.mb-30
          %a.close.general-cart-close{'aria-label': "Close", 'data-method': 'put',
            href: cart_path(delete: 'true', product: order_item.product_id)}
          %span{'aria-hidden': "true"} &times;
          .general-img-wrap-table
            %a{href: product_path(order_item.product_id)}
              %img.cart-img-shadow.width-full{src: order_item.product.product_pictures(1).first.image_path}
          %p.general-title= order_item.product.title
          %table.table
            %tr
              %td
                %span.in-grey-600 Price
              %td
                %span.font-16.in-gold-500= number_to_currency(order_item.unit_price, unit: '€')
            %tr
              %td.vertical-middle
                %span.in-grey-600 Quantity
              %td
                = fields_for 'order_items[]', order_item.product_id do |field_item|
                  .input-group
                    %a.input-link{href: "#"}
                      %i.fa.fa-minus.line-height-40
                    = field_item.text_field :quantity, type: "text", class: 'form-control quantity-input', min: 1, value: "#{order_item.quantity}"
                    %a.input-link{href: "#"}
                      %i.fa.fa-plus.line-height-40
            %tr
              %td
                %span.in-grey-600 SubTotal
              %td
                %span.font-16.in-gold-500= number_to_currency(order_item.subtotal, unit: '€')
      .general-order-wrap
        .row
          .col-sm-4
            = fields_for @coupon do |coupon|
              .input-group.general-input-group
                %label.font-weight-light Enter Your Coupon Code
                = coupon.text_field :code, type: "text", class: 'form-control mb-30', placeholder: "Enter Your Coupon Code "
                %div
                  %button.btn.btn-primary.mr-5.mb-15.visible-xs-inline-block{name: "coupon_only", value: "true"} Apply Coupon
                  %button.btn.btn-primary.mb-15.res-block.update-cart Update cart
          .col-sm-8
            .res-mr-200.text-center.general-text-right
              %p.in-gold-500.font-18 Order Summary
              %table.general-summary-table.general-summary-table-right.general-text-right
                %tr
                  %td
                    %p.font-16 Subtotal:
                  %td
                    %p.font-16= number_to_currency(@order.subtotal_price, unit: '€')
                %tr
                  %td
                    %p.font-16 Coupon:
                  %td
                    %p.font-16= number_to_currency(@order.discount, unit: '€')
                %tr
                  %td
                    %strong.font-18 Order Total:
                  %td
                    %strong.font-18= number_to_currency(@order.total_price, unit: '€')
              %a.btn.btn-default.mb-20.visible-xs-inline-block{href: checkout_path} Checkout
      %a.btn.btn-default.mb-20.hidden-xs.center-block.checkout-btn{href: checkout_path} Checkout
  .hidden-xs
    = form_tag cart_path,  method: :put do |field|
      %table.table.table-hover
        %tr.no-hover
          %th.col-pic.pl-0
            %span.in-grey-600 Product
          %th.col-title
          %th.col-price
            %span.in-grey-600 Price
          %th.col-quantity
            %span.in-grey-600 Quantity
          %th.col-total
            %span.in-grey-600 SubTotal
          %th.col-close
        - @order_items.each  do |order_item|
          %tr
            %td
              .general-img-wrap-table
                %a{href: product_path(order_item.product_id)}
                  %img.cart-img-shadow.pull-left.width-full{src: order_item.product.product_pictures(1).first.image_path}
            %td
              %p.general-title= order_item.product.title
            %td
              %span.font-16.in-gold-500= number_to_currency(order_item.unit_price, unit: '€')
            %td
              = fields_for 'order_items[]', order_item.product_id do |field_item|
                .input-group
                  %a.input-link{href: "#"}
                    %i.fa.fa-minus.line-height-40
                  = field_item.text_field :quantity, type: "text", class: 'form-control quantity-input', min: 1, value: "#{order_item.quantity}"
                  %a.input-link{href: "#"}
                    %i.fa.fa-plus.line-height-40
            %td
              %span.font-16.in-gold-500= number_to_currency(order_item.subtotal, unit: '€')
            %td
              %a.close.general-cart-close{href: cart_path(delete: 'true', product: order_item.product_id),
                'aria-label': "Close", 'data-method': 'put'}
                %span{'aria-hidden': "true"} &times;
      .general-order-wrap
        .row
          .col-sm-4
            = fields_for @coupon do |coupon|
              .input-group.general-input-group
                %label.font-weight-light Enter Your Coupon Code
                = coupon.text_field :code, type: "text", class: 'form-control mb-30', placeholder: "Enter Your Coupon Code "
                %div
                  %button.btn.btn-primary.mr-5.mb-15.visible-xs-inline-block Apply Coupon
                  %button.btn.btn-primary.mb-15.res-block.update-cart Update cart
          .col-sm-8
            .res-mr-200.text-center.general-text-right
              %p.in-gold-500.font-18 Order Summary
              %table.general-summary-table.general-summary-table-right.general-text-right
                %tr
                  %td
                    %p.font-16 Subtotal:
                  %td
                    %p.font-16= number_to_currency(@order.subtotal_price, unit: '€')
                %tr
                  %td
                    %p.font-16 Coupon:
                  %td
                    %p.font-16= number_to_currency(@order.discount, unit: '€')
                %tr
                  %td
                    %strong.font-18 Order Total:
                  %td
                    %strong.font-18= number_to_currency(@order.total_price, unit: '€')
              %a.btn.btn-default.mb-20.visible-xs-inline-block{href: engine_cart.checkout_path} Checkout
      %a.btn.btn-default.mb-20.hidden-xs.center-block.checkout-btn{href: engine_cart.checkout_path} Checkout